sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.1
  - 2.5.2
gemfile:
  - gemfiles/activerecord-51.gemfile
  - gemfiles/activerecord-52.gemfile
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
env:
  - DB=sqlite
  - DB=mysql MYSQL_RESTART_COMMAND="sudo service mysql restart"
  - NO_TIMESTAMP=false
  - NO_TIMESTAMP=true
