sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4.1
  - 2.3.3
gemfile:
  - gemfiles/activerecord-42.gemfile
  - gemfiles/activerecord-50.gemfile
  - gemfiles/activerecord-51.gemfile
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
env:
  - DB=sqlite
  - DB=mysql MYSQL_RESTART_COMMAND="sudo service mysql restart"
